n1 = int(input('Digite o primeiro numero: '))
n2 = int(input('Digite o segundo numero: '))
print(f'A soma vale {n1 + n2}')
print(f'A subtração vale {n1 - n2}')
print(f'A multiplicação vale {n1 * n2}')
print(f'A divisão vale {n1 / n2:.2f}')
print(f'A potência vale {n1 ** n2}')
print(f'A divisão inteira vale {n1 // n2}')
print(f'O resto da divisão vale {n1 % n2}')